INSERT INTO FLIGHT (FLIGHT_NO, CAPACITY, FROM_STATION, TO_STATION, FROM_CODE, TO_CODE, DEPARTURE, ARRIVAL, PRICE) 
VALUES ('111', 300, 'AHMEDABAD', 'MUMBAI', 'AHD', 'MUM', '2023-09-15 10.00.00', '2023-09-15 12.00.00', 4000.00 );
INSERT INTO FLIGHT (FLIGHT_NO, CAPACITY, FROM_STATION, TO_STATION, FROM_CODE, TO_CODE, DEPARTURE, ARRIVAL, PRICE) 
VALUES ('222', 200, 'MUMBAI', 'AHMEDABAD', 'MUM', 'AHD', '2023-09-15 14.00.00', '2023-09-15 16.00.00', 3999.99 );
INSERT INTO FLIGHT (FLIGHT_NO, CAPACITY, FROM_STATION, TO_STATION, FROM_CODE, TO_CODE, DEPARTURE, ARRIVAL, PRICE) 
VALUES ('333', 400, 'MUMBAI', 'DELHI', 'MUM', 'DHL', '2023-09-15 06.30.00', '2023-09-15 08.45.00', 1299.95 );
INSERT INTO FLIGHT (FLIGHT_NO, CAPACITY, FROM_STATION, TO_STATION, FROM_CODE, TO_CODE, DEPARTURE, ARRIVAL, PRICE) 
VALUES ('444', 100, 'DELHI', 'MUMBAI', 'DHL', 'MUM', '2023-09-12 09.30.00', '2023-09-12 13.12.00', 1895.95 );
INSERT INTO FLIGHT (FLIGHT_NO, CAPACITY, FROM_STATION, TO_STATION, FROM_CODE, TO_CODE, DEPARTURE, ARRIVAL, PRICE) 
VALUES ('555', 100, 'AHMEDABAD', 'MUMBAI', 'AHD', 'MUM', '2023-09-15 18.30.00', '2023-09-15 20.00.00', 2040 );

INSERT INTO TICKET (FLIGHT_ID) VALUES (1);
INSERT INTO TICKET (FLIGHT_ID) VALUES (1);
INSERT INTO TICKET (FLIGHT_ID) VALUES (1);
INSERT INTO TICKET (FLIGHT_ID) VALUES (1);
INSERT INTO TICKET (FLIGHT_ID) VALUES (2);
INSERT INTO TICKET (FLIGHT_ID) VALUES (2);
INSERT INTO TICKET (FLIGHT_ID) VALUES (2);
INSERT INTO TICKET (FLIGHT_ID) VALUES (2);
INSERT INTO TICKET (FLIGHT_ID) VALUES (3);
INSERT INTO TICKET (FLIGHT_ID) VALUES (3);
INSERT INTO TICKET (FLIGHT_ID) VALUES (3);
INSERT INTO TICKET (FLIGHT_ID) VALUES (3);

INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-01', 'PASSPORT_01', 25, 'INDIAN', 1);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-02', 'PASSPORT_02', 26, 'INDIAN', 1);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-03', 'PASSPORT_03', 27, 'INDIAN', 2);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-04', 'PASSPORT_04', 28, 'INDIAN', 2);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-05', 'PASSPORT_05', 29, 'INDIAN', 3);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-06', 'PASSPORT_06', 30, 'INDIAN', 4);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-07', 'PASSPORT_07', 31, 'INDIAN', 4);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-08', 'PASSPORT_08', 5, 'INDIAN', 5);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-09', 'PASSPORT_09', 32, 'INDIAN', 6);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-10', 'PASSPORT_10', 36, 'INDIAN', 7);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-11', 'PASSPORT_11', 23, 'INDIAN', 7);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-12', 'PASSPORT_12', 32, 'INDIAN', 8);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-13', 'PASSPORT_13', 36, 'INDIAN', 8);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-14', 'PASSPORT_14', 23, 'INDIAN', 8);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-15', 'PASSPORT_15', 31, 'INDIAN', 9);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-16', 'PASSPORT_16', 5, 'INDIAN', 10);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-17', 'PASSPORT_17', 32, 'INDIAN', 10);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-18', 'PASSPORT_18', 36, 'INDIAN', 11);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-19', 'PASSPORT_19', 23, 'INDIAN', 11);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-20', 'PASSPORT_20', 32, 'INDIAN', 12);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-21', 'PASSPORT_21', 36, 'INDIAN', 12);
INSERT INTO PASSENGER (NAME, PASSPORT_NO, AGE, NATIONALITY, TICKET_ID) VALUES ('Passenger-22', 'PASSPORT_22', 23, 'INDIAN', 12);
