create table FLIGHT (
	ID INT NOT NULL AUTO_INCREMENT,
	FLIGHT_NO VARCHAR(100) NOT NULL,
	CAPACITY INT NOT NULL,
	FROM_STATION VARCHAR(100) NOT NULL,
	TO_STATION VARCHAR(100) NOT NULL,
	FROM_CODE VARCHAR(100),
	TO_CODE VARCHAR(100),
	DEPARTURE TIMESTAMP ,
	ARRIVAL TIMESTAMP,
	PRICE DOUBLE,
	PRIMARY KEY ( ID ),
	UNIQUE (FLIGHT_NO)
);

create table TICKET (
	ID INT NOT NULL AUTO_INCREMENT,
	FLIGHT_ID INT,
	PRIMARY KEY ( ID )
);

CREATE TABLE PASSENGER (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	PASSPORT_NO VARCHAR(100) ,
	AGE INT,
	NATIONALITY VARCHAR(100),
	TICKET_ID INT, 
	PRIMARY KEY ( ID )
);
